#!/bin/bash
# left button action
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
	firefox https://beaker.engineering.redhat.com/jobs/mine 
fi
UNFINISHED_JOBS=$(bkr job-list --mine --format list --unfinished | wc -l)
echo "$UNFINISHED_JOBS"
